version: '3'

services:

  mysql:
    container_name: mysql-tasks
    image: mysql:latest
    ports:
      - "8005:3306"
    environment:
      MYSQL_USER: xavi
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Tasks
    volumes:
      - tasks-data-mysql:/var/lib/mysql
    restart: always

volumes:
  tasks-data-mysql:
    name: tasks-data-mysql