spring:
  application:
    name: user-service


  #### BBDD AND JPA CONFIG ###
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:8004}/${DB_NAME:Auth}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    ### CONNECTION POOL####
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      pool-name: ${DB_POOL_NAME:AuthDatabasePool}

  ### JPA ###
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.MySQLDialect}

  ### LIQUIBASE ###
  liquibase:
    change-log: classpath:db/changelog.xml


  #### MULTIPART FILE CONFIG ###
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:200MB}
      max-request-size: ${MAX_REQUEST_SIZE:215MB}


server:
  servlet:
    session:
      #### TIMEOUT ###
      timeout: ${SESSION_TIMOUT:60s}

  #### PORT ###
  port: ${PORT:${SERVER_PORT:0}}


#### SWAGGER ###
openapi:
  service:
    title: user-service doc
    version: 1.0.0
    url: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080} #api gateway url
springdoc:
  api-docs:
    path: v3/api-docs
  swagger-ui:
    path: swagger-ui.html


#### EUREKA ###
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true


### CIRCUIT BREAKER ###
resilience4j.circuitbreaker:
  instances:
    taskCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - java.net.ConnectException
        - feign.FeignException$ServiceUnavailable