spring:
  application:
    name: eureka-service

### PORT ###
server:
  port: ${PORT:8761}


### EUREKA ###
eureka:
  instance:
    hostname: eureka-service
  client:
    fetch-registry: false
    register-with-eureka: false

