
name: Auth Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'auth-service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: cd auth-service && mvn --batch-mode package -U
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: auth-build-artifacts
          path: auth-service/target/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: auth-build-artifacts
          path: auth-service/target/
      - name: Run Tests with Maven
        run: cd auth-service && mvn --batch-mode test
